config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/plan'
  root 'documents#new'

  # auth
  get '/logout', to: 'sessions#logout', as: :logout
  post '/login', to: 'sessions#login', as: :login

  # documents
  resources :documents, only: [:index, :new, :create] do
    get '/download', action: :download
    get '/check', action: :check
  end

  # users
  resources :students, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  default_scope { order(created_at: :desc) }

  belongs_to :student
  belongs_to :checker, class_name: "Student", optional: true

  mount_uploader :file, Document::FileUploader
end

app/models/student.rb
class Student < ApplicationRecord
  has_one :document, dependent: :destroy
  has_many :checked_documents, class_name: "Document", foreign_key: "checker_id", dependent: :nullify

  validates :name, uniqueness: true

  AVAILABLE_STUDENTS = [
      'Peter Bariš',
      'Maroš Benka',
      'Slavomír Cimbalista',
      'Pavol Dravecký',
      'Jakub Dzurilla',
      'Peter Fedorek',
      'Martin Galovič',
      'Lukáš Garnek',
      'Roman Grék',
      'Matúš Hudák',
      'Sebastián Hutník',
      'Branislav Janči',
      'Martin Jaseňák',
      'Daniel Kormanský',
      'Ján Krempaský',
      'Adam Kuruc',
      'Juraj Marec',
      'Martin Maskaľ',
      'Lukáš Mišanko',
      'Ján Olšavský',
      'Daniel Pisarčík',
      'Richard Sankovský',
      'Dávid Schwartz',
      'Filip Slebodník',
      'Samuel Slebodník',
      'Dominik Šulian',
      'Dávid Tokarčík',
      'Martin Valluš',
      'Tomáš Zajac',
      'Maroš Zummer'
  ].freeze

  def self.pending_names
    except = Document.all.map {|d| d.student.name}
    AVAILABLE_STUDENTS - except
  end

  def verified?
    document&.checked? || false
  end

  def admin?
    blacklist = ["Roman Grék", "Lukáš Mišanko"]
    blacklist.exclude?(name)
  end

  def superadmin?
    whitelist = ["Martin Galovič"]
    whitelist.include?(name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:download, :check]
  before_action :authenticate_student!, only: [:download]

  def index
    @status_presenter = StatusPresenter.new
    @documents = Document.all
  end

  def new
    redirect_to documents_path, flash: { info: "jedno zadanie staci, uz nenahravaj dalsie" } if current_student&.document
    @document = Document.new
    @student = Student.new
  end

  def create
    redirect_to documents_path, flash: { info: "jedno zadanie staci, uz nenahravaj dalsie" } if current_student&.document

    @student = Student.new(name: document_params[:student], pin: ('%05d' % rand(10 ** 5)))
    @document = Document.new

    if @student.save
      @document = Document.create!(student: @student, file: document_params[:file])

      flash[:success] = "Odovzdane, modli sa zeby to nebola picovina, tvoj PIN: <strong>#{@student.pin}</strong>"
      redirect_to documents_path
    else
      render :new
    end

  end

  def download
    redirect_to @document.file.url
  end

  def check
    @document.checked = !@document.checked?
    @document.checker = current_student
    @document.save!
    redirect_to documents_path, flash: { success: "Overene" }
  end

  private

  def document_params
    params.require(:document).permit(:student, :file)
  end

  def set_document
    @document = Document.find(params[:document_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    if student_signed_in?
      redirect_back fallback_location: root_path, flash: { info: "uz si prihlaseny" }
    end

    student = Student.find_by_pin(params[:pin])
    if student && student.verified?
      student_login(student.id)
      redirect_back fallback_location: documents_path, flash: { success: "dobre, stahuj, uc sa" }
    elsif student && student.verified? == false
      redirect_back fallback_location: documents_path, flash: { info: "chvilku pockaj kym overime ci si picovinu neposlal" }
    else
      redirect_to documents_path, flash: { danger: "nedobry pin" }
    end

  end

  def logout
    student_logout
    redirect_to documents_path, flash: { success: "BB" }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def plan
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student
  before_action :authenticate_student!

  def destroy
    if @student.destroy
      redirect_to documents_path, flash: { success: "deleted #{@student.name}" }
    else
      redirect_to documents_path, flash: { danger: "not deleted #{@student.name}" }
    end
  end

  private

  def set_student
    @student = Student.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def student_signed_in?
    not current_student.nil?
  end

  def current_student
    Student.find_by(id: session[:student_id])
  end

  def authenticate_student!
    return redirect_to documents_path, status: :temporary_redirect, flash: { danger: 'nono ty vytržnik' } unless student_signed_in?
  end

  def student_login(student_id)
    session[:student_id] = student_id
  end

  def student_logout
    session.delete(:student_id)
  end
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/document/index.html.haml
%h1 Document#index
%p Find me in app/views/document/index.html.haml

app/views/documents/_sign_in.haml
.row
  .col-sm-6.offset-sm-3
    .card
      .card-body
        .card-title
          %h5 Prihlas sa
        = form_with url: login_path, local: true, class: 'form-horizontal' do |f|
          .form-group
            = f.label :pin
            = f.password_field :pin, size: 5, class: 'form-control', placeholder: '*****'
          .form-group
            = f.submit "Prihlasit sa", class: 'btn btn-block btn-primary'

app/views/documents/index.haml
.container
  - unless student_signed_in?
    = render partial: 'sign_in'
  - else
    = render partial: 'partials/status', locals: { presenter: @status_presenter }
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Kto
            %th Kedy
            %th Overene?
            %th.text-right Download
        %tbody
          - @documents.each do |document|
            %tr{class: "#{document.student_id == current_student.id ? 'table-warning' : ''}"}
              %td
                = "#{document.student_id == current_student.id ? "<b>--> tvoje </b>" : ""} #{h(document.student.name)}".html_safe
                = "<br>pin: <b>#{document.student.pin}</b>".html_safe if current_student.superadmin?
                = link_to "- destroy", student_path(document.student), method: :delete, data: { confirm: 'isto?' } if current_student.superadmin?

              %td= "#{document.created_at.strftime("%A")}, #{document.created_at.to_formatted_s(:short)}"
              %td
                - if document.checked?
                  %span.text-success= fa_icon "check", text: "Hej vsetko poodicke"
                  = link_to "zrusit overenie", document_check_path(document) if current_student.admin?
                - else
                  %span.text-danger= fa_icon "times", text: "Zatial nie"
                  = link_to "overit", document_check_path(document) if current_student.admin?

              %td.text-right
                = link_to "Download", document_download_path(document), class: 'btn btn-sm btn-info'

app/views/documents/new.haml
.container
  .jumbotron
    %h1 Nahraj svoje vypracovanie
    %p Grek nebud kokot a normalne zvol svoje meno, ked to nahras jak dakto iny tak sa to dojebe a uz sa to neda spatne odjebat

    .row
      .col-lg-6
        - if @student.errors.any?
          .alert.alert-danger
            %ul
              - @student.errors.full_messages.each do |msg|
                %li= msg

        = form_for @document, local: true, class: 'form-horizontal' do |f|
          .form-group
            = f.label :student, "Kto si"
            = f.select :student, Student.pending_names, {}, class: 'form-control', required: true
          .form-group
            = f.label :file, "Nahraj subor (pdf)"
            = f.file_field :file, class: 'form-control', required: true, accept: '.pdf,.doc,.docx'

          .alert.alert-danger
            Skontroluj ci si vybral spravne meno!
          .form-group
            = f.submit "Odovzdat", class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", name: "viewport", id: 'viewport'}/

    %title IV.EA Tezy
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light.mb-5
      %a.navbar-brand{:href => root_path} IV.EA Tezy
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item
            %a.nav-link{:href => root_path}
              Nahrat vypracovanie
              %span.sr-only
          %li.nav-item
            %a.nav-link{:href => documents_path} Vsetky vypracovania

    .container
      - if flash[:success].present?
        .alert.alert-success
          = flash[:success].html_safe
      - if flash[:danger].present?
        .alert.alert-danger
          = flash[:danger].html_safe
      - if flash[:info].present?
        .alert.alert-info
          = flash[:info].html_safe

      - if student_signed_in?
        %p
          = "Si prihlaseny ako <b>#{current_student.name}</b>, pin: <b data-pin='#{current_student.pin}'>*****</b>".html_safe
          |
          = link_to "Odhlasit sa", logout_path

    = yield

app/views/partials/_status.haml
%hr
.progress
  .progress-bar{style: "width: #{presenter.progress_width}%"}= "#{presenter.sent_names.size} / #{presenter.all_names.size}"
%p
  %small.text-muted
    = "<b>Poponahlajte totych kokotov nech to poslu:</b> #{h(presenter.pending_names.join(', '))}".html_safe
%br

app/views/static_pages/plan.html.haml
.container
  %h2
    %pre
      -# TODO ...